<div class="content">
    <h2><?php echo $this->escape($this->mail['subject']) ?></h2>
    <div class="information">
        <p class="received"><span class="header">Sent: </span><span><?php echo $this->escape($this->mail['date']) ?></span></p>
        <p class="from"><span class="header">From: </span><span class="user_male"><?php echo $this->escape($this->mail['from']) ?></span></p>
        <p class="to"><span class="header">To: </span><span class="user_male"><?php echo $this->escape($this->mail['to']) ?></span></p><?php
if(!empty($this->mail['cc'])): ?>
        <p class="cc"><span class="header">CC: </span><?php echo $this->escape($this->mail['cc']) ?></p><?php endif;
if(!empty($this->mail['bcc'])): ?>
        <p class="bcc"><span class="header">BCC: </span><?php echo $this->escape($this->mail['bcc']) ?></p><?php endif;  ?>
    </div>
    <div class="menu">
        <div class="left"><span class="button"><a class="reply" href="#">Reply</a></span><span class="button"><a class="reply_all" href="#">Reply all</a></span><span class="button"><a class="forward" href="#">Forward</a></span></div>
        <div class="right"><span class="button"><a class="mail_history" href="#">Mail history</a></span><span class="button"><a class="add_note" href="#">Add Note</a></span></div>
    </div>
    <div class="mail_content">
<?php if(empty($this->mail['html'])): ?>
        <div class="textview">
            <pre><?php echo $this->escape($this->mail['text']) ?></pre>
        </div><?php else: ?>
        <div class="htmlview">
    <?php echo $this->mail['html'] ?>
        </div><?php endif;?>
    </div>
</div>